//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// First.rc에서 사용되고 있습니다.
//
#define TXT_CLKR                        5
#define IDB_BITMAP1                     106
#define IDB_BITMAP2                     107
#define IDB_BITMAP3                     108
#define IDB_BITMAP4                     109
#define IDB_BITMAP5                     110
#define IDB_BITMAP6                     111
#define IDB_BITMAP7                     112
#define IDB_BITMAP8                     113
#define IDB_BITMAP9                     114
#define IDB_BITMAP10                    115
#define IDB_BITMAP11                    116
#define IDB_BITMAP12                    117
#define IDB_BITMAP13                    118
#define IDB_BITMAP14                    120
#define IDB_BITMAP15                    121
#define IDB_BITMAP16                    122
#define IDB_BITMAP17                    123
#define Weapon_Shoot_1                  146
#define Weapon_Shoot_2                  154
#define IDB_BITMAP21                    161
#define IDB_BITMAP18                    167
#define IDB_ROUND                       170
#define IDB_BITMAP19                    171
#define IDB_BITMAP20                    172
#define IDB_BITMAP22                    173
#define IDB_BITMAP23                    174
#define IDB_BITMAP24                    175
#define IDB_BITMAP25                    176
#define IDB_ROUND1                      177
#define IDB_ROUND2                      178
#define IDB_ROUND3                      179
#define IDB_ROUND4                      180
#define IDB_BITMAP27                    182
#define IDB_BITMAP28                    183
#define IDB_BITMAP29                    184
#define IDB_BITMAP30                    185
#define IDB_BITMAP31                    186
#define IDB_BITMAP32                    187
#define IDB_BITMAP33                    188
#define IDB_BITMAP34                    189
#define IDB_BITMAP35                    190
#define IDB_BITMAP36                    191
#define IDB_BITMAP37                    192
#define IDB_BITMAP38                    193
#define IDB_BITMAP39                    194
#define IDB_BITMAP40                    195
#define IDB_BITMAP26                    240
#define IDB_BITMAP41                    241
#define IDB_BITMAP42                    242
#define IDB_BITMAP43                    243
#define IDB_BITMAP44                    244
#define IDB_BITMAP45                    245
#define IDB_BITMAP46                    246
#define IDB_BITMAP47                    247
#define IDB_BITMAP48                    248
#define IDB_BITMAP49                    249
#define IDB_BITMAP50                    250
#define IDB_BITMAP51                    251
#define IDB_BITMAP52                    252
#define IDB_BITMAP53                    253
#define IDB_BITMAP54                    254
#define IDB_BITMAP55                    255
#define IDB_BITMAP56                    256
#define IDB_BITMAP57                    257
#define IDB_BITMAP58                    258
#define IDB_BITMAP59                    259
#define IDB_BITMAP60                    260
#define IDB_BITMAP61                    261
#define IDB_BITMAP62                    262
#define IDB_BITMAP63                    263
#define IDB_BITMAP64                    264
#define IDB_BITMAP65                    265
#define IDB_BITMAP66                    266
#define IDB_BITMAP67                    267
#define IDB_BITMAP68                    268
#define IDB_BITMAP69                    269
#define IDB_BITMAP70                    270
#define IDB_LAST1                       271
#define IDB_LAST10                      272
#define IDB_LAST11                      273
#define IDB_LAST12                      274
#define IDB_LAST28                      275
#define IDB_LAST13                      276
#define IDB_LAST14                      277
#define IDB_LAST9                       278
#define IDB_LAST8                       279
#define IDB_LAST7                       280
#define IDB_LAST6                       281
#define IDB_LAST5                       282
#define IDB_LAST4                       283
#define IDB_LAST31                      284
#define IDB_LAST30                      285
#define IDB_LAST3                       286
#define IDB_LAST29                      287
#define IDB_LAST27                      288
#define IDB_LAST15                      289
#define IDB_LAST20                      290
#define IDB_LAST25                      291
#define IDB_LAST24                      292
#define IDB_LAST23                      293
#define IDB_LAST22                      294
#define IDB_LAST26                      295
#define IDB_LAST18                      296
#define IDB_LAST16                      297
#define IDB_LAST17                      298
#define IDB_LAST19                      299
#define IDB_LAST2                       300
#define IDB_LAST21                      301
#define IDB_GFACE                       302
#define IDB_BARBG                       303
#define IDB_FACE                        304
#define IDB_HPBAR                       305
#define IDB_LEVEL                       306
#define IDB_LEVELBAR                    307
#define FX_fall1                        308
#define FX_fall2                        309
#define FX_fall3                        310
#define FX_fall4                        311
#define FX_fall5                        312
#define FX_fall6                        313
#define FX_fall7                        314
#define IDB_BITMAP71                    315
#define IDB_BITMAP72                    316
#define IDB_BITMAP73                    317
#define IDB_BITMAP74                    318
#define IDB_BITMAP75                    319
#define IDB_BITMAP76                    320
#define IDB_BITMAP77                    321
#define IDB_BITMAP78                    322
#define IDB_BITMAP79                    323
#define IDB_BITMAP80                    324
#define IDB_BITMAP81                    325
#define IDB_BITMAP82                    326
#define IDB_BITMAP83                    327
#define IDB_BITMAP84                    328
#define IDB_BITMAP85                    329
#define IDB_BITMAP86                    330
#define IDB_BITMAP87                    331
#define IDB_BITMAP88                    332
#define IDB_BITMAP89                    333
#define IDB_BITMAP90                    334
#define IDB_BITMAP91                    335
#define IDB_BITMAP92                    336
#define IDB_BITMAP93                    337
#define IDB_FRAME                       337
#define IC_LAST                         338
#define IC_ROUND                        339
#define IC_SHOOT                        340
#define IC_FALL                         341
#define TXT_DMGPLUS                     342
#define TXT_CLKSCN                      343
#define TXT_HPPLUS                      344
#define TXT_SPDPLUS                     345
#define TXT_TITLE                       346
#define TXT_WADD                        347
#define TXT_WPLUS                       348
#define IDB_BOUNCE1                     349
#define IDB_BOUNCE2                     350
#define IC_BOUNCE                       351
#define P_MALE1                         352
#define P_MALE2                         353
#define P_MALE3                         354
#define P_MALE4                         355
#define TXT_CLKL                        356
#define IDB_MFACE                       358
#define IDB_BITMAP94                    359
#define TXT_END                         359

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        360
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
